config/routes.rb
Dreamforge::Application.routes.draw do
  devise_for :users

  resources :forums, :only => [:show, :index]
  resources :categories
  resources :topics, :only => [:show]
  resources :posts, :only => [:create]

  root :to => "static_pages#home"
end

app/models/ability.rb
# @attr [String] name, required
# @attr [Text] description, required
# @attr [Hash] actions, required

class Ability < Gist
  validates_format_of :type, :with => /\AAbility\z/

  serialize :actions, Hash

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :actions
  validates_format_of :fictional_author, :with => /\A\z/
end

app/models/category.rb
# @attr [String] name is shown in the community, required
# @attr [String] subtitle is shown in the community, optional
# @attr [Array] forums is a list of dependend forums, that will be destroyed, when the area is destroyed

class Category < ActiveRecord::Base
  validates_presence_of :name

  has_many :forums, :dependent => :destroy
end

app/models/forum.rb
# @attr [String] name is shown in the community, required
# @attr [String] subtitle is shown in the community, optional
# @attr [Category] category is the {Category} it depends on
# @attr [Array] topics is a list containg each and every {Topic} depending on it. Will be destroyed, when the forum is destroyed.

class Forum < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :category

  belongs_to :category
  delegate :name, :to => :category, :prefix => true
  has_many :topics, :dependent => :destroy
end

app/models/gist.rb
# The Gist uses SingleTableInheritance and should not be created without type

class Gist < ActiveRecord::Base
  belongs_to :topic
end

app/models/mod.rb
# @attr [String] name, required
# @attr [Text] description, required

class Mod < Gist
  validates_format_of :type, :with => /\AMod\z/

  validates_presence_of :name
  validates_presence_of :description
  validates_format_of :actions, :with => /\A\z/
  validates_format_of :fictional_author, :with => /\A\z/
end

app/models/post.rb
# @attr [Text] content, required. Should be written as Markdown.
# @attr [Topic] topic, required
# @attr [User] user, required

class Post < ActiveRecord::Base
  validates_presence_of :content
  validates_presence_of :topic
  validates_presence_of :user

  belongs_to :topic
  belongs_to :user
  delegate :name, :to => :user, :prefix => true

  # @return [Text] post formatted as HTML.
  def to_html
    Post.to_html(content)
  end

  # @param [Text] text the text you would like to transform to HTML.
  # @return [Text] post formatted as HTML.
  def Post.to_html(text)
    RDiscount.new(text, :filter_html).to_html
  end
end

app/models/profession.rb
# @attr [String] name, required
# @attr [Text] description, required

class Profession < Gist
  validates_format_of :type, :with => /\AProfession\z/

  validates_presence_of :name
  validates_presence_of :description
  validates_format_of :actions, :with => /\A\z/
  validates_format_of :fictional_author, :with => /\A\z/
end

app/models/race.rb
# @attr [String] name, required
# @attr [Text] description, required

class Race < Gist
  validates_format_of :type, :with => /\ARace\z/

  validates_presence_of :name
  validates_presence_of :description
  validates_format_of :actions, :with => /\A\z/
  validates_format_of :fictional_author, :with => /\A\z/
end

app/models/rule.rb
# @attr [String] name, required
# @attr [Text] description, required

class Rule < Gist
  validates_format_of :type, :with => /\ARule\z/

  validates_presence_of :name
  validates_presence_of :description
  validates_format_of :actions, :with => /\A\z/
  validates_format_of :fictional_author, :with => /\A\z/
end

app/models/story.rb
# @attr [String] name, required
# @attr [Text] description, required
# @attr [String] fictional_author, required

class Story < Gist
  validates_format_of :type, :with => /\AStory\z/

  validates_presence_of :name
  validates_presence_of :description
  validates_format_of :actions, :with => /\A\z/
  validates_presence_of :fictional_author
end

app/models/topic.rb
# @attr [String] title is shown in lists and so on, required
# @attr [Forum] forum it belongs to, required

class Topic < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :forum

  belongs_to :forum
  delegate :name, :to => :forum, :prefix => true

  has_many :posts, :dependent => :destroy

  has_one :gist
end

app/models/user.rb
# The User Model is devise-powered
# Has eMail, Password, Name.
# TODO: GOOD Documentation

class User < ActiveRecord::Base
  devise :database_authenticatable, # encrypts and stores password while signing in
         :registerable, # handles signing up / edit / destroy users through a registration process
         :recoverable, # recover password via email
         :rememberable, # cookies
         :validatable # validate email and password

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :posts

  before_destroy :make_undead

  validates :name, :presence => true,
                   :uniqueness => { :case_sensitive => false }
  validates :email, :presence => true, :format => { :with => /\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i}

  def zombie?
    read_attribute(:zombie)
  end

  private

  def make_undead
    write_attribute(:zombie, true)
    write_attribute(:email, nil)

    # Not stored in the database, but as a matter of principle:
    @password = nil
    @password_confirmation = nil

    save(:validate => false)

    # Return false so ActiveRecord will not erase the object from the database.
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @forum = Forum.find(params[:id])
    # @topics = @forum.topics.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    @topics = @forum.topics
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @post = current_user.posts.build(params[:post])

    if @post.save
      flash[:success] = t('post.create.flash.success')
      redirect_to :controller => :topics, :action => :show, :id => @post.topic
    else
      flash[:error] = t('post.create.flash.error')
      # Redirect to the login page
      redirect_to new_user_session_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = Topic.find params[:id]
    @posts = @topic.posts

    @post = Post.new

    @post.topic = @topic if user_signed_in?
  end
end

app/views/forums/index.html.haml
- @categories.each do |category|
  %table.category
    %thead
      %tr
        %td= category.name
    %tbody
      - category.forums.each do |forum|
        %tr
          %td= link_to forum.name, forum

app/views/forums/show.html.haml
%h2= @forum.name

%ol.breadcrumbs
  %li= link_to t(:community), '/forums'
  %li= @forum.category_name
  %li= @forum.name

%table.topics
  %thead
    %tr
      %td= t(:topics)
  %tbody
    - @topics.each do |topic|
      %tr
        %td= link_to topic.title, topic

/= will_paginate @topics

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Dreamforge
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
  %body= yield

app/views/posts/_create_form.html.haml
= form_for @post do |f|
  = f.hidden_field :topic_id
  = f.label :content, t('post.create.label.content')
  = f.text_area :content
  = f.submit "Post"

app/views/posts/_post.html.haml
= form_for post do |f|
  = f.hidden_field :topic_id
  = f.label :content, t('post.create.label.content')
  = f.text_area :content
  = f.submit t('post.create.submit')

app/views/static_pages/home.html.haml
%h1 StaticPages#home
%p Find me in app/views/static_pages/home.html.haml

app/views/topics/show.html.haml
%h2= @topic.title

%ol.breadcrumbs
  %li= link_to t(:community), forums_path
  %li= @topic.forum.category_name
  %li= link_to @topic.forum_name, @topic.forum
  %li= @topic.title

#userbox
  - if user_signed_in?
    %p= t('user.welcome', username: current_user.name)
  - else
    = link_to t('user.login'), user_session_path

- flash.each do |key, value|
  %div{:class => "flash #{key}"}
    = value

%table.posts
  - @posts.each do |post|
    %tr
      %td= post.user_name
      %td= raw post.to_html

- if user_signed_in?
  = render @post

/= will_paginate @posts

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/